---
version: "3.9"
services:
  marquee-updater:
    container_name: marquee-updater
    image: marquee
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/docker/marquee:/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: python -u /app/marquee-updater.py > /dev/ttyUSB0
    restart: always
  maruqee-ui:
    container_name: marquee-ui
    image: marquee
    environment:
      - FLASK_APP=/app/marquee-ui.py
    volumes:
      - /mnt/docker/marquee:/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    command: python -u -m flask run --host=0.0.0.0 --port=80 --with-threads
    restart: always

