DELETE FROM messages;

INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Red", 1, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Green", 2, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Amber", 3, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Rainbow 1", 4, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Rainbow 2", 5, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Color Mix", 6, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Autocolor", 7, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Five High STD", 1, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Seven High STD", 1, 2, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Seven High Fancy", 1, 3, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Rotate", 1, 1, 1);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Hold", 1, 1, 2);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Roll Up", 1, 1, 3);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Roll Down", 1, 1, 4);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Roll Left", 1, 1, 5);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Roll Right", 1, 1, 6);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Wipe Up", 1, 1, 7);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Wipe Down", 1, 1, 8);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Wipe Left", 1, 1, 9);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Wipe Right", 1, 1, 10);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Scroll", 1, 1, 11);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Roll In", 1, 1, 12);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Roll Out", 1, 1, 13);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Wipe In", 1, 1, 14);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Wipe Out", 1, 1, 15);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Twinkle", 1, 1, 16);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Sparkle", 1, 1, 17);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Snow", 1, 1, 18);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Interlock", 1, 1, 19);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Switch", 1, 1, 20);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Spray", 1, 1, 21);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Starburst", 1, 1, 22);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Welcome", 1, 1, 23);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Slot Machine", 1, 1, 24);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Thank You", 1, 1, 25);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("No Smoking", 1, 1, 26);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Don't Drink and Drive", 1, 1, 27);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Running Animal", 1, 1, 28);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Fireworks", 1, 1, 29);
INSERT INTO messages (text, color_id, font_id, mode_id) VALUES ("Turbo Car", 1, 1, 30);